image: node:8.4.0

stages:
  - build
  - test

cache:
  key: yarn_cache
  paths:
    - .yarn_cache

build:
  script:
    - npm install yarn
    - yarn install --cache-folder ./.yarn_cache

test:
  stage: test
  script:
    - yarn test -- --ci --runInBand
